image: node:10.16

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .npm/
  - public/

before_script:
  - npm ci --cache .npm --prefer-offline
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - pip install awscli

stages:
  - build
  - deploy

build-production:
  stage: build
  script:
    - npm install
    - npm run clean
    - npm run build

deploy-to-aws:
  stage: deploy
  script:
    - ./deploy.sh
  only:
    - master
