image: node:10.16

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .npm/
  - public/
  - .cache/
  - node_modules/
  - .cache/pip

before_script:
  - npm ci --cache .npm --prefer-offline
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - pip install awscli

stages:
  - install_deps
  - build
  - deploy

install-dependencies:
  stage: install_deps
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm install

build-project:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - .cache/
    - public/
  script:
    - npm run clean
    - npm run build

deploy-to-aws:
  stage: deploy
  script:
    - ./deploy.sh
  only:
    - master
