image: node:10.16

variables:
  AWS_DEFAULT_REGION: eu-central-1

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build-stage:
  stage: build
  script:
    - npm install
    - ./node_modules/.bin/gatsby build
  artifacts:
    paths:
      - public

deploy-stage:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME} --recursive
    - aws s3 cp --recursive public s3://${BUCKET_NAME}
  only:
    - master
